### ISSUE TITLE
Paper link in Readme.md fails

### ISSUE THREAD

**Issue by swartn** [andim/optimmune#1]
Thanks for this example of #openscience. Just a note that in the Readme the link below fails:

```
[How a well adapted immune system is organized](http://dx.doi.org/10.1073/pnas.1421827112)
```

**Comment by andim** [comment]
Thanks @swartn for the remark. It seems like the doi might still take some time to be activated. Here is a direct link: http://www.pnas.org/content/early/2015/04/24/1421827112

**Comment by andim** [comment]
The doi is now activated and the link is working properly.
